import { spawnSync } from "node:child_process"
import path from "node:path"
import { beforeEach, describe, expect, it, vi } from "vitest"

import { CliError } from "../../packages/cli/lib/output.mjs"
import {
  detectProject,
  findAliasRoot,
  install,
} from "../../packages/cli/lib/project.mjs"
import { createProject } from "./helpers.mjs"

vi.mock("node:child_process", () => ({
  spawnSync: vi.fn(() => ({ status: 0 })),
}))

const tsconfig = { compilerOptions: {} }

describe("detectProject", () => {
  it("recognises a Next.js project", () => {
    const cwd = createProject({
      "package.json": { dependencies: { next: "16.0.0", react: "19.0.0" } },
      "tsconfig.json": tsconfig,
    })
    expect(detectProject(cwd)).toMatchObject({ cwd, framework: "next" })
  })

  it("recognises a React project built with Vite", () => {
    const cwd = createProject({
      "package.json": {
        dependencies: { react: "19.0.0" },
        devDependencies: { vite: "7.0.0" },
      },
      "tsconfig.json": tsconfig,
    })
    expect(detectProject(cwd).framework).toBe("vite")
  })

  it("rejects a folder without package.json", () => {
    const cwd = createProject({})
    expect(() => detectProject(cwd)).toThrow(CliError)
  })

  it("rejects projects that are neither Next.js nor React with Vite", () => {
    const cwd = createProject({
      "package.json": { devDependencies: { vite: "7.0.0" } },
      "tsconfig.json": tsconfig,
    })
    expect(() => detectProject(cwd)).toThrow(
      "Only Next.js and React (Vite) projects are supported."
    )
  })

  it("requires TypeScript", () => {
    const cwd = createProject({
      "package.json": { dependencies: { next: "16.0.0" } },
    })
    expect(() => detectProject(cwd)).toThrow("tsconfig.json not found")
  })

  it.each([
    ["pnpm-lock.yaml", "pnpm"],
    ["yarn.lock", "yarn"],
    ["bun.lock", "bun"],
    ["package-lock.json", "npm"],
  ])("detects the package manager from %s", (lockfile, manager) => {
    const cwd = createProject({
      "package.json": { dependencies: { next: "16.0.0" } },
      "tsconfig.json": tsconfig,
      [lockfile]: "",
    })
    expect(detectProject(cwd).packageManager).toBe(manager)
  })

  it("finds the lockfile of a parent workspace", () => {
    const root = createProject({
      "pnpm-lock.yaml": "",
      "apps/web/package.json": { dependencies: { next: "16.0.0" } },
      "apps/web/tsconfig.json": tsconfig,
    })
    const project = detectProject(path.join(root, "apps/web"))
    expect(project.packageManager).toBe("pnpm")
  })
})

describe("findAliasRoot", () => {
  it("resolves the @/* alias against baseUrl", () => {
    const cwd = createProject({
      "tsconfig.json": {
        compilerOptions: { baseUrl: ".", paths: { "@/*": ["./src/*"] } },
      },
    })
    expect(findAliasRoot(cwd)).toBe(path.join(cwd, "src"))
  })

  it("reads tsconfig files with comments and trailing commas", () => {
    const cwd = createProject({
      "tsconfig.json": `{
  // generated by create-next-app
  "compilerOptions": {
    /* aliases */
    "paths": { "@/*": ["./*"], },
  },
}`,
    })
    expect(findAliasRoot(cwd)).toBe(cwd)
  })

  it("falls back to tsconfig.app.json", () => {
    const cwd = createProject({
      "tsconfig.json": { files: [] },
      "tsconfig.app.json": {
        compilerOptions: { paths: { "@/*": ["./src/*"] } },
      },
    })
    expect(findAliasRoot(cwd)).toBe(path.join(cwd, "src"))
  })

  it("returns null when no alias is configured", () => {
    const cwd = createProject({ "tsconfig.json": tsconfig })
    expect(findAliasRoot(cwd)).toBeNull()
  })
})

describe("install", () => {
  const project = (packageManager) => ({
    cwd: "/project",
    packageManager,
    packages: { react: "19.0.0" },
  })

  beforeEach(() => {
    vi.mocked(spawnSync).mockClear()
    vi.mocked(spawnSync).mockReturnValue({ status: 0 })
  })

  it("installs only packages that are missing, once each", () => {
    const target = project("pnpm")
    const installed = install(target, ["react", "cmdk", "cmdk", "recharts"])
    expect(installed).toEqual(["cmdk", "recharts"])
    expect(spawnSync).toHaveBeenCalledWith(
      "pnpm",
      ["add", "cmdk", "recharts"],
      expect.objectContaining({ cwd: "/project" })
    )
    expect(target.packages.cmdk).toBe("*")
  })

  it("skips the package manager when everything is installed", () => {
    expect(install(project("npm"), ["react"])).toEqual([])
    expect(spawnSync).not.toHaveBeenCalled()
  })

  it.each([
    ["npm", ["install", "--save-dev", "tailwindcss"]],
    ["pnpm", ["add", "--save-dev", "tailwindcss"]],
    ["yarn", ["add", "--dev", "tailwindcss"]],
    ["bun", ["add", "--dev", "tailwindcss"]],
  ])("uses the dev flag of %s", (manager, args) => {
    install(project(manager), ["tailwindcss"], { dev: true })
    expect(spawnSync).toHaveBeenCalledWith(manager, args, expect.anything())
  })

  it("fails when the package manager fails", () => {
    vi.mocked(spawnSync).mockReturnValue({ status: 1 })
    expect(() => install(project("npm"), ["cmdk"])).toThrow(
      "npm install cmdk failed."
    )
  })

  it.each(["cmdk & calc", "--registry=http://evil", "../local"])(
    "refuses the invalid package name %s",
    (name) => {
      expect(() => install(project("npm"), [name])).toThrow(
        `Refusing to install an invalid package name: ${name}`
      )
      expect(spawnSync).not.toHaveBeenCalled()
    }
  )
})
